### ISSUE TITLE
[이서용][08/25]

### ISSUE THREAD

**Issue by seoyong-lee** [codestates/codestory2.0#271]
### 오늘은 어떻게 프로젝트에 기여했나요?

- 오늘은 랜딩 페이지를 완성하고 관련 오류 해결 및 리팩토링을 진행하였습니다.

### 오늘의 프로젝트에서 느낀 점이나 기억에 남는 점은 무엇인가요? (필수 1개)

- CSS Modules 에서 :global을 이용한 전역화가 잘 진행되지 않아 그동안 main.scss 에서 작성하였던 코드를 드디어 해결하였습니다. sass의 중첩 문법 안에 :global( 선택자 ) 와 같은 식으로 작성하니 정상적으로 전역화가 되었고, 이를 통해 main.scss를 다시 간소화 할 수 있었습니다. CSS Modules의 공식 github 에서도 언급되지 않았던 부분이라 스택 오버플로우를 통해 찾을 수 있었습니다.

```css
.game {
  position: relative;
  margin: auto;
}
:global(#css_game_container) {
  width: 670px;
  height: 775px;
}

/* 위와 같은 방식은 작동하지 않았으며, 아래와 같이 중첩을 통해 해결함 */

.game {
  position: relative;
  margin: auto;
  :global(#css_game_container) {
    width: 670px;
    height: 775px;
  }
}
```

[스택 오버플로우 관련 링크](https://stackoverflow.com/questions/65985543/selector-global-class-is-not-pure-pure-selectors-must-contain-at-least-one)

### 내일은 프로젝트에 기여하기 위해 무엇을 해야 하나요?

- [ ] 마지막 리뷰 준비
